permalink: /posts/:title
markdown: kramdown
theme: jekyll-theme-minimal

#gems:
# - jekyll-sitemap

name: Eric Ernst
url: https://egernst.github.io
description: Things and stuff I learned
twitter: egernst
